version: '3.8'

services:
  api:
    build: .
    container_name: nest-api
    restart: always
    ports:
      - '3001:3001'
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/mydb
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - PORT=${PORT}
      - BETTER_STACK_URL=${BETTER_STACK_URL}
      - BETTER_STACK_TOKEN=${BETTER_STACK_TOKEN}
      - INSTAGRAM_SERVICE_URL=${INSTAGRAM_SERVICE_URL}
    command: yarn start:prod

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
