name: Deploy to Staging

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to staging
    runs-on: ubuntu-22.04

    steps:
      - name: Testar secrets
        run: echo "Secrets configuradas corretamente!"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Validar GH_TOKEN
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          RESPONSE=$(curl -s -H "Authorization: token $GH_TOKEN" https://api.github.com/user)
          if echo "$RESPONSE" | grep -q "login"; then
            echo "✅ GH_TOKEN válido!"
          else
            echo "❌ GH_TOKEN inválido ou sem permissão!"
            exit 1
          fi

      - name: Checkout do repositório
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.x

      - name: Install semver CLI
        run: npm install -g semver

      - name: Instalar dependências
        run: yarn

      - name: Build da aplicação
        run: yarn build

      - name: Criar nova tag caso não exista
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          if [ -z "$(git tag)" ]; then
            git config --global user.name 'github-actions'
            git config --global user.email 'github-actions@github.com'
            git tag -a v0.0.0 -m "Initial release"
            git push origin v0.0.0
          fi

      - name: Calcular nova versão
        id: version
        run: |
          git fetch --tags
          LAST_TAG=$(git tag --sort=-v:refname | grep -E '^v?[0-9]+\.[0-9]+\.[0-9]+$' | head -n 1)
          if [ -z "$LAST_TAG" ]; then
            LAST_TAG="v0.0.0"
          fi
          echo "Versão Atual: $LAST_TAG"

          CURRENT_VERSION=${LAST_TAG#v}

          MAJOR=0
          MINOR=0
          PATCH=0

          if [ "$LAST_TAG" = "v0.0.0" ]; then
            COMMITS=$(git log --pretty=format:"%s")
          else
            COMMITS=$(git log ${LAST_TAG}..HEAD --pretty=format:"%s")
          fi

          echo "Commits desde a última tag:"
          echo "$COMMITS"

          while read -r COMMIT; do
            if [[ "$COMMIT" == *"BREAKING CHANGE"* ]]; then
              MAJOR=1
            elif [[ "$COMMIT" == *"feat"* ]]; then
              MINOR=1
            elif [[ "$COMMIT" == *"fix"* ]]; then
              PATCH=1
            fi
          done <<< "$COMMITS"

          if [[ $MAJOR -eq 1 ]]; then
            NEW_VERSION=$(semver -i major $CURRENT_VERSION)
          elif [[ $MINOR -eq 1 ]]; then
            NEW_VERSION=$(semver -i minor $CURRENT_VERSION)
          elif [[ $PATCH -eq 1 ]]; then
            NEW_VERSION=$(semver -i patch $CURRENT_VERSION)
          else
            NEW_VERSION=$CURRENT_VERSION
          fi

          echo "Nova versão: $NEW_VERSION"
          echo "new_version=$NEW_VERSION" >> $GITHUB_ENV

      - name: Atualizar versão no package.json
        run: |
          CURRENT_PKG_VERSION=$(node -p "require('./package.json').version")
          if [ "$CURRENT_PKG_VERSION" != "$new_version" ]; then
            npm version "$new_version" --no-git-tag-version
            echo "Versão atualizada para $new_version"
          else
            echo "A versão já é $new_version, nenhuma alteração necessária."
          fi

      - name: Commit e push
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

          if [ -n "$(git status --porcelain)" ]; then
            git add package.json
            git commit -m "chore(release): version $new_version"
            if git rev-parse "v$new_version" >/dev/null 2>&1; then
              echo "Tag v$new_version já existe, ignorando..."
            else
              git tag "v$new_version"
              git push origin "v$new_version"
            fi
            git push origin main --follow-tags
          else
            echo "Nenhuma mudança para commit"
          fi
