name: CI e CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: Integração Contínua (CI)
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.x

      - name: Instalar dependências
        run: yarn

      - name: Build da aplicação
        run: yarn build

      - name: Rodar testes
        run: yarn test

      - name: Rodar lint
        run: yarn lint

  cd:
    name: Entrega Contínua (CD)
    runs-on: ubuntu-22.04
    needs: ci
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.x

      - name: Instalar semver CLI
        run: npm install -g semver

      - name: Instalar dependências
        run: yarn

      - name: Build da aplicação
        run: yarn build

      - name: Criar nova tag caso não exista
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          if [ -z "$(git tag)" ]; then
            git config --global user.name 'github-actions'
            git config --global user.email 'github-actions@github.com'
            git tag -a v0.0.0 -m "Initial release"
            git push origin v0.0.0
          fi

      - name: Calcular nova versão
        id: version
        run: |
          git fetch --tags
          LAST_TAG=$(git tag --sort=-v:refname | grep -E '^v?[0-9]+\.[0-9]+\.[0-9]+$' | head -n 1)
          if [ -z "$LAST_TAG" ]; then
            LAST_TAG="v0.0.0"
          fi
          echo "Versão Atual: $LAST_TAG"

          CURRENT_VERSION=${LAST_TAG#v}
          MAJOR=0
          MINOR=0
          PATCH=0

          if [ "$LAST_TAG" = "v0.0.0" ]; then
            COMMITS=$(git log --pretty=format:"%s")
          else
            COMMITS=$(git log ${LAST_TAG}..HEAD --pretty=format:"%s")
          fi

          echo "Commits desde a última tag:"
          echo "$COMMITS"

          while read -r COMMIT; do
            if [[ "$COMMIT" == *"BREAKING CHANGE"* ]]; then
              MAJOR=1
            elif [[ "$COMMIT" == *"feat"* ]]; then
              MINOR=1
            elif [[ "$COMMIT" == *"fix"* ]]; then
              PATCH=1
            fi
          done <<< "$COMMITS"

          if [[ $MAJOR -eq 1 ]]; then
            NEW_VERSION=$(semver -i major $CURRENT_VERSION)
          elif [[ $MINOR -eq 1 ]]; then
            NEW_VERSION=$(semver -i minor $CURRENT_VERSION)
          elif [[ $PATCH -eq 1 ]]; then
            NEW_VERSION=$(semver -i patch $CURRENT_VERSION)
          else
            NEW_VERSION=$CURRENT_VERSION
          fi

          echo "Nova versão: $NEW_VERSION"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Definir o nome do repositório
        run: |
          REPO_NAME="${{ github.repository }}"
          REPO_NAME="${REPO_NAME#*/}"
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV 
          echo "Repositório: $REPO_NAME"

      - name: Criar imagem docker
        run: |
          echo "Iniciando build da imagem Docker para o repositório $REPO_NAME - Versão: ${{ env.NEW_VERSION }}"
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/$REPO_NAME:${{ env.NEW_VERSION }} .
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/$REPO_NAME:${{ env.NEW_VERSION }} ${{ secrets.DOCKERHUB_USERNAME }}/$REPO_NAME:latest

      - name: Efetuar push da imagem
        run: |
          echo "Fazendo push da imagem Docker para o Docker Hub ${{ secrets.DOCKERHUB_USERNAME }}/$REPO_NAME:${{ env.NEW_VERSION }}"
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/$REPO_NAME:${{ env.NEW_VERSION }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/$REPO_NAME:latest

      - name: Deploy to Render.com
        run: |
          echo "Disparando deploy na Render..."
          curl -X POST https://api.render.com/deploy/srv-d1fc59mr433s73b4dc3g?key=YvA-A4sJwhk

      - name: Atualizar versão no package.json
        run: |
          CURRENT_PKG_VERSION=$(node -p "require('./package.json').version")
          if [ "$CURRENT_PKG_VERSION" != "${{ env.NEW_VERSION }}" ]; then
            npm version "${{ env.NEW_VERSION }}" --no-git-tag-version
            echo "Versão atualizada para ${{ env.NEW_VERSION }}"
          else
            echo "A versão já é ${{ env.NEW_VERSION }}, nenhuma alteração necessária."
          fi

      - name: Commit e push
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          if [ -n "$(git status --porcelain)" ]; then
            git add package.json
            git commit -m "chore(release): version ${{ env.NEW_VERSION }}"
            if git rev-parse "v${{ env.NEW_VERSION }}" >/dev/null 2>&1; then
              echo "Tag v${{ env.NEW_VERSION }} já existe, ignorando..."
            else
              git tag "v${{ env.NEW_VERSION }}"
              git push origin "v${{ env.NEW_VERSION }}"
            fi
            git push origin main --follow-tags
          else
            echo "Nenhuma mudança para commit"
          fi
